Fix bug in torch compile and seqdim is integer
NVIDIA/TransformerEngine pull request #1217
Opened 2024-09-29 08:55 UTC by wplf

# Description

When NVTE_TORCH_COMPILE is 0 and  jit_fuser will be torch.jit.script.
And they don't accept interger, bug will occur in the function below  due to the `seq_dim` argument.
 

```
@jit_fuser
def flash_attn_fwd_out_correction(out, out_per_step, seq_dim, softmax_lse, softmax_lse_per_step):
    """Merge partial outputs of each step in Attention with context parallelism"""
    softmax_lse_corrected_exp = torch.exp(softmax_lse_per_step - softmax_lse).movedim(2, seq_dim)
    softmax_lse_corrected_exp = softmax_lse_corrected_exp.unsqueeze(-1)
    out_corrected = out_per_step * softmax_lse_corrected_exp
    out.add_(out_corrected)
```

Fixes # (issue)

## Type of change

- [ ] Documentation change (change only to the documentation, either a fix or a new content)
- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Infra/Build change
- [ ] Code refractor

## Changes

Please list the changes introduced in this PR:

- Change A
- Change B

# Checklist:

- [ ] I have read and followed the [contributing guidelines](https://github.com/NVIDIA/TransformerEngine/blob/main/CONTRIBUTING.rst)
- [ ] The functionality is complete
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes

2024-09-30 19:38 UTC, ksivaman requested changes
@wplf Can we not annotate `flash_attn_fwd_out_correction` instead? IIUC, the fusers assume every argument is a tensor unless explicitly specified.

2024-10-01 00:58 UTC, wplf commented
> @wplf Can we not annotate `flash_attn_fwd_out_correction` instead? IIUC, the fusers assume every argument is a tensor unless explicitly specified.

That's right. Torch.jit.fuser need arguments to be tensor, but torch.compiler don't. 
I am afraid removing the annotation will degrade performance in the case of `torch.complie`.

2024-10-01 01:55 UTC, ksivaman commented
Let's try and annotate the function and see if it fixes the error!

2024-10-02 16:01 UTC, wplf commented
> Let's try and annotate the function and see if it fixes the error!

I have checked that removing the annotation will fix the problem. And the pull request is changed, too.

2024-10-02 16:03 UTC, ksivaman commented
I don't see the changes yet, could you update the PR?

2024-10-02 16:06 UTC, wplf commented
> I don't see the changes yet, could you update the PR?

Sorry, I don't expect you so quickly like that. You can check it now.

2024-10-02 17:47 UTC, ksivaman commented on transformer_engine/pytorch/attention.py
>  def flash_attn_fwd_out_correction(out, out_per_step, seq_dim, softmax_lse, softmax_lse_per_step):
```suggestion
@jit_fuser
def flash_attn_fwd_out_correction(
    out: torch.Tensor,
    out_per_step: torch.Tensor,
    seq_dim: int,
    softmax_lse: ... #TODO,
    softmax_lse_per_step: ...#TODO,
):
```

2024-10-02 17:48 UTC, ksivaman commented
We still want the `jit_fuser` decorator instead of forcing it to be `torch.compile`. What I meant by annotating is to add explicit types to the arguments. See given suggestion (just an example)

2024-10-10 15:29 UTC, ksivaman commented
@wplf Could you see if the new changes resolve the error?

2024-10-10 16:03 UTC, ksivaman commented
/te-ci pytorch

2024-10-10 16:18 UTC, xrennvidia commented
LGTM.

2024-10-11 17:59 UTC, merged