[COMMON/JAX] Support sliding window on THD format
NVIDIA/TransformerEngine pull request #1327
Opened 2024-11-11 07:57 UTC by zlsh80826

# Description

Support THD format with sliding window

## Type of change

- [ ] Documentation change (change only to the documentation, either a fix or a new content)
- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Infra/Build change
- [ ] Code refractor

## Changes

- [COMMON] Relax the condition for THD + sliding window
- [COMMON] Replace THD with `is_ragged` and `BSHD||SBHD` with `!is_ragged` in `nvte_get_fused_attn_backend`
- [JAX] Add some util functions for `AttnMaskType`

# Checklist:

- [x] I have read and followed the [contributing guidelines](https://github.com/NVIDIA/TransformerEngine/blob/main/CONTRIBUTING.rst)
- [x] The functionality is complete
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes

2024-11-11 07:58 UTC, zlsh80826 commented
/te-ci jax L1

2024-11-11 07:58 UTC, zlsh80826 commented
/te-ci

2024-11-11 14:26 UTC, mgoldfarb-nvidia commented on transformer_engine/jax/attention.py
> +    def is_causal(self):
Nice pythonic helpers!

2024-11-12 18:07 UTC, cyanguwa commented on transformer_engine/common/fused_attn/fused_attn.cpp
> +             (is_ragged && attn_mask_type == NVTE_Mask_Type::NVTE_PADDING_CAUSAL_MASK) ||
Could you factor the self-attn bottom_right combination into this condition as well?
```
(!is_ragged && (attn_mask_type == NVTE_Mask_Type::NVTE_CAUSAL_MASK || (attn_mask_type == NVTE_Mask_Type::NVTE_CAUSAL_BOTTOM_RIGHT_MASK && max_seqlen_q == max_seqlen_kv))) || (is_ragged && (attn_mask_type == NVTE_Mask_Type::NVTE_PADDING_CAUSAL_MASK || (attn_mask_type == NVTE_Mask_Type::NVTE_PADDING_CAUSAL_BOTTOM_RIGHT_MASK && max_seqlen_q == max_seqlen_kv))) 
```

2024-11-12 18:08 UTC, cyanguwa approved these changes
Other than that one comment, LGTM, thanks!

2024-11-12 22:05 UTC, huanghua1994 requested changes
The changes to the code LGTM. The CI builds failed, need to check and re-run.

2024-11-12 22:19 UTC, mgoldfarb-nvidia approved these changes

2025-01-06 08:23 UTC, zlsh80826 commented
Close as duplicated with #1378 and #1390

2025-01-06 08:23 UTC, closed without merging