Shriya/tp overlap patch
NVIDIA/TransformerEngine pull request #205
Opened 2023-05-09 20:27 UTC by ShriyaPalsamudram

Upstreaming @erhoo82's branch: [tp_overlap_patch](https://github.com/erhoo82/TransformerEngine/commits/tp_overlap_patch)

2023-05-09 20:28 UTC, ptrendx commented on transformer_engine/pytorch/cpp_extensions.py
> +    layer_name: int = 9,
Why 9?

2023-05-09 20:28 UTC, ShriyaPalsamudram commented
@ptrendx @ksivaman please review, thanks.

2023-05-09 20:30 UTC, ptrendx commented on transformer_engine/pytorch/csrc/userbuffers/userbuffers.h
> +//void userbuffers_alltoall_recv(communicator *comm, cudaStream_t stream = 0);
Same

2023-05-09 20:32 UTC, ksivaman commented on transformer_engine/pytorch/module.py
> +                    layer_name=4,
Why are all these hardcoded? @ShriyaPalsamudram

2023-05-09 22:40 UTC, timmoon10 requested changes
If I understand correctly, the only functional change is to change some memory accesses to use `atomicAdd_system`. We also add some more information to an error message, which requires plumbing in the `layer_name` throughout the whole PyTorch infrastructure. If this debugging info is not absolutely essential, I feel the extra messiness is not worth it. At the very least, `layer_name` is a really awkward name and should be changed to something like `ub_layer_id` or `ub_layer_label`.

2023-05-09 22:58 UTC, ShriyaPalsamudram commented
Agreed, removed the logging commit from this PR

2023-05-09 23:32 UTC, ptrendx approved these changes

2023-05-09 23:40 UTC, timmoon10 approved these changes
LGTM

2023-05-09 23:50 UTC, ptrendx commented
@ShriyaPalsamudram please sign your commit.

2023-05-10 01:27 UTC, ksivaman approved these changes

2023-05-10 17:22 UTC, merged