[C/PyTorch] Minor improvements for fused attention
NVIDIA/TransformerEngine pull request #453
Opened 2023-10-03 00:31 UTC by cyanguwa

This PR 
- adjusts the support for fused attention in preparation of upcoming cuDNN releases, and
- reduces the number of unit tests in PyTorch fused_attn.py.

2023-10-03 00:33 UTC, cyanguwa commented
Pipeline 10079370

2023-10-06 20:42 UTC, cyanguwa commented
/te_ci

2023-10-06 20:45 UTC, cyanguwa commented
/te-ci

2023-10-06 20:53 UTC, cyanguwa commented
/te-ci

2023-10-06 21:08 UTC, cyanguwa commented
/te-ci

2023-10-06 21:24 UTC, cyanguwa commented
/te-ci pytorch

2023-10-06 21:30 UTC, timmoon10 requested changes

2023-10-06 21:30 UTC, timmoon10 commented on transformer_engine/pytorch/attention.py
> +        pretrained_max_position_embeddings: int = None,
```suggestion
        seq_len_interpolation_factor: Optional[int] = None,
        pretrained_max_position_embeddings: Optional[int] = None,
```

2023-10-06 21:30 UTC, timmoon10 commented on transformer_engine/pytorch/attention.py
> +        return rearrange(emb, 'n d -> n 1 1 d')
Could we remove the einops dependency?
```suggestion
        return emb.reshape(emb.size(0), 1, 1, emb.size(1))
```

2023-10-06 21:33 UTC, ksivaman commented on transformer_engine/pytorch/attention.py
> +from einops import rearrange
Let's use `.transpose` instead @cyanguwa

2023-10-09 18:51 UTC, cyanguwa commented on transformer_engine/pytorch/attention.py
> +        pretrained_max_position_embeddings: int = None,
Done

2023-10-09 19:00 UTC, cyanguwa commented on transformer_engine/pytorch/attention.py
> +from einops import rearrange
Thanks - I'm adopting Tim's suggestion.

2023-10-09 19:01 UTC, cyanguwa commented on transformer_engine/pytorch/attention.py
> +        return rearrange(emb, 'n d -> n 1 1 d')
Thanks!

2023-10-09 19:01 UTC, cyanguwa commented
/te-ci

2023-10-09 20:39 UTC, timmoon10 approved these changes
LGTM

2023-10-09 20:44 UTC, ksivaman approved these changes
LGTM

2023-10-09 23:09 UTC, cyanguwa commented
All CI has passed (10173716), merging.

2023-10-09 23:12 UTC, merged