Add GeGLU and the corresponding gradient kernels
NVIDIA/TransformerEngine pull request #47
Opened 2022-12-28 15:57 UTC by zlsh80826

1. [GeGLU](https://arxiv.org/pdf/2002.05202.pdf) is used in T5. Fusing `gelu`, `gate`, `elementwise_mul` can highly reduce the global memory read/write and increase the performance. Two backward kernels are also added, `dgeglu` is for `fp16`, `bf16`, `fp32`, and `dgeglu_cast_transpose` is for `fp8` output.
2. Because `geglu` and `dgeglu` has multiple input/outputs. This PR extends `CheckAlignment` to support multiple input/outputs.
3. Move `gelu` and `dgelu` to `util/math.h`

2022-12-28 15:58 UTC, zlsh80826 commented
/te-ci

2023-01-06 12:43 UTC, zlsh80826 commented
/te-ci

2023-01-07 01:19 UTC, timmoon10 requested changes

2023-01-09 05:25 UTC, zlsh80826 commented on transformer_engine/common/util/math.h
> +}
Done by [6b1fe29b19cf82c08f834592acd90324a7a5a7c0](https://github.com/NVIDIA/TransformerEngine/pull/47/commits/6b1fe29b19cf82c08f834592acd90324a7a5a7c0)

2023-01-09 05:26 UTC, zlsh80826 commented on transformer_engine/common/util/vectorized_pointwise.h
> +      storer.separate()[i] = static_cast<OutputType>(static_cast<ComputeType>(temp));
Done by [6b1fe29b19cf82c08f834592acd90324a7a5a7c0](https://github.com/NVIDIA/TransformerEngine/pull/47/commits/6b1fe29b19cf82c08f834592acd90324a7a5a7c0)

2023-01-09 05:26 UTC, zlsh80826 commented on transformer_engine/common/transpose/cast_transpose_fusion.cu
> +             "C and T outputs need to have the same type.");
Done by [6b1fe29b19cf82c08f834592acd90324a7a5a7c0](https://github.com/NVIDIA/TransformerEngine/pull/47/commits/6b1fe29b19cf82c08f834592acd90324a7a5a7c0)

2023-01-09 05:26 UTC, zlsh80826 commented on transformer_engine/common/util/vectorized_pointwise.h
> +      storer1.separate()[i] = static_cast<OutputType>(static_cast<ComputeType>(after_dgate));
Done by [6b1fe29b19cf82c08f834592acd90324a7a5a7c0](https://github.com/NVIDIA/TransformerEngine/pull/47/commits/6b1fe29b19cf82c08f834592acd90324a7a5a7c0)

2023-01-09 05:30 UTC, zlsh80826 commented on tests/cpp/operator/test_cast_transpose_dgeglu.cu
> +                                                     {256, 5120}, {128, 10240}, {256, 256}};
non-nice numbers are not supported by cast_transpose_fusion kernel :slightly_frowning_face:
[ct_dbias](https://github.com/NVIDIA/TransformerEngine/blob/main/tests/cpp/operator/test_cast_transpose_dbias.cu#L130-L136)
[ct_dbias_dgelu](https://github.com/NVIDIA/TransformerEngine/blob/main/tests/cpp/operator/test_cast_transpose_dbias_dgelu.cu#L147-L152)

2023-01-09 05:30 UTC, zlsh80826 commented
/te-ci

2023-01-09 18:24 UTC, timmoon10 commented on tests/cpp/operator/test_cast_transpose_dgeglu.cu
> +                                                     {256, 5120}, {128, 10240}, {256, 256}};
Ah bummer, did you run into problems when running? We should throw an error in that case instead of launching the non-aligned kernel.

2023-01-09 18:25 UTC, timmoon10 approved these changes
I'd like to throw an error when running `cast_transpose_dgeglu` with non-nice dims, but otherwise this LGTM.

2023-01-10 13:56 UTC, zlsh80826 commented
> I'd like to throw an error when running `cast_transpose_dgeglu` with non-nice dims, but otherwise this LGTM.

Yes, [error will be throw](https://github.com/NVIDIA/TransformerEngine/blob/6b1fe29b19cf82c08f834592acd90324a7a5a7c0/transformer_engine/common/transpose/cast_transpose_fusion.cu#L1509-L1510) if the dims are not suppported

2023-01-10 16:00 UTC, zlsh80826 commented on tests/cpp/operator/test_cast_transpose_dgeglu.cu
> +                                                     {256, 5120}, {128, 10240}, {256, 256}};
Yes, [error will be throw](https://github.com/NVIDIA/TransformerEngine/blob/6b1fe29b19cf82c08f834592acd90324a7a5a7c0/transformer_engine/common/transpose/cast_transpose_fusion.cu#L1509-L1510) if the dims are not suppported

2023-01-10 22:43 UTC, merged