[PyTorch] Workaround for incorrect output from torch.cuda.is_bf16_compatible() on V100s and TU102s
NVIDIA/TransformerEngine pull request #626
Opened 2024-01-23 20:10 UTC by denera

[A recent PyTorch API change for `torch.cuda.is_bf16_compatible()`](https://github.com/pytorch/pytorch/commit/fc5fda14bcc41008e5610bf39c53eb066933ea4e) makes the check intentionally more permissive to support `torch.bfloat16` Tensors on some older GPUs. This has caused CI failures for us on V100 and TU102 nodes because TorchInductor supports `torch.bfloat16` only for sm_80 or higher.

This PR replaces `torch.cuda.is_bf16_compatible()` checks with explicit checks on `torch.cuda.get_device_capability()[0] >= 8` to comply with TorchInductor limitations.

2024-01-23 20:10 UTC, denera commented
/te-ci pytorch

2024-01-23 20:13 UTC, ksivaman approved these changes
LGTM, sounds like this is a PyTorch bug?

2024-01-23 20:23 UTC, denera commented
> LGTM, sounds like this is a PyTorch bug?

It's not clear to me whether they knew that there are some components of the PyTorch that don't support Bf16 for devices older than sm_80, or if they knew but still wanted to be more permissive because a most core components will work fine regardless.

I can file an issue with them about this, but at least this PR will de-couple us from whatever they decide to do with the API down the line.

2024-01-23 21:12 UTC, ptrendx requested changes
Could you actually add a function to utils that has a correct behavior (like te.utils.is_bf16_compatible()`)?

2024-01-23 21:40 UTC, denera commented
/te-ci PyTorch

2024-01-23 21:43 UTC, denera commented
/te-ci pytorch

2024-01-23 22:20 UTC, ptrendx approved these changes

2024-01-24 00:50 UTC, nWEIdia approved these changes
Looks great!

2024-01-24 15:32 UTC, merged