New fp8_transpose_dbias kernel
NVIDIA/TransformerEngine pull request #73
Opened 2023-02-13 21:40 UTC by vasunvidia

Signed-off-by: Vasudevan Rengasamy <vrengasamy@nvidia.com>

2023-03-18 04:17 UTC, ksivaman commented
/te-ci

2023-03-20 18:53 UTC, timmoon10 requested changes
Overall looks good, code is mostly the same as https://github.com/NVIDIA/TransformerEngine/blob/main/transformer_engine/common/transpose/cast_transpose_fusion.cu. The NVTX macro is most important suggestion. Removing some unused variables would also help clean up the code.

2023-03-20 18:53 UTC, timmoon10 commented on transformer_engine/common/transpose/transpose_fusion.cu
> +    OVecC out_cast;
Unused variable:
```suggestion
```

2023-03-20 18:53 UTC, timmoon10 commented on transformer_engine/common/transpose/transpose_fusion.cu
> +                                                             const bool valid_store) {
Unused args:
```suggestion
template <int nvec_in, int nvec_out,
          typename IVec, typename OVec, typename CVec, typename CType>
inline __device__ void transpose_regs_partial_dbias(const IVec (&in)[nvec_out],
                                                             OVec (&out_trans)[nvec_in],
                                                             CVec &out_dbias,  // NOLINT(*)
                                                             const CType scale_inv,
                                                             const int dbias_shfl_src_lane) {
```

2023-03-20 18:53 UTC, timmoon10 commented on transformer_engine/common/transpose/transpose_fusion.cu
> +  using namespace transformer_engine;
Missing NVTX marker:
```suggestion
  NVTE_API_CALL(nvte_transpose_dbias);
  using namespace transformer_engine;
```

2023-03-20 20:06 UTC, ksivaman commented
/te-ci

2023-03-20 20:20 UTC, timmoon10 approved these changes
LGTM

2023-03-20 20:21 UTC, ksivaman approved these changes

2023-03-21 00:17 UTC, merged